import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProfileCheck } from "@/components/ProfileCheck";
import { Navbar } from "@/components/Navbar";
import { BanGate } from "@/components/BanGate";
import { Footer } from "@/components/Footer";
import { BookingChatWidget } from "@/components/chat/BookingChatWidget";
import { Toaster } from "@/components/ui/toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50/40">
        <ProfileCheck />
        <Navbar />
        <main className="flex-1 flex flex-col">
          <BanGate>{children}</BanGate>
        </main>
        <Footer />
        <BookingChatWidget />
        <Toaster />
      </body>
    </html>
  );
}
